# Colors (Pencil Light)
 # primary:
   # background: '#ffffff'
   # foreground: '#424242'
 # normal:
   # black:   '#212121'
   # red:     '#c30771'
   # green:   '#10a778'
   # yellow:  '#a89c14'
   # blue:    '#008ec4'
   # magenta: '#523c79'
   # cyan:    '#20a5ba'
   # white:   '#e0e0e0'
 # bright:
   # black:   '#212121'
   # red:     '#fb007a'
   # green:   '#5fd7af'
   # yellow:  '#f3e430'
   # blue:    '#20bbfc'
   # magenta: '#6855de'
   # cyan:    '#4fb8cc'
   # white:   '#f1f1f1'
colors:
 primary:
   background: '#ffffff'
   foreground: '#424242'
 # Normal colors
 normal:
   black:   '#212121'
   red:     '#c30771'
   green:   '#10a778'
   yellow:  '#a89c14'
   blue:    '#008ec4'
   magenta: '#523c79'
   cyan:    '#20a5ba'
   white:   '#e0e0e0'
 # Bright colors
 bright:
   black:   '#212121'
   red:     '#fb007a'
   green:   '#5fd7af'
   yellow:  '#f3e430'
   blue:    '#20bbfc'
   magenta: '#6855de'
   cyan:    '#4fb8cc'
   white:   '#f1f1f1'

font:
  normal:
    family: Menlo
    style: Regular
  bold:
    family: Menlo
    style: Bold
  italic:
    family: Menlo
    style: Italic
  bold_italic:
    family: Source Code Pro
    style: Bold Italic
  size: 12.0
  offset:
    x: 1
    y: 2

window:
  padding:
    x: 10
    y: 2
  decorations: none

selection:
  save_to_clipboard: true

key_bindings:
  - { key: Left,    mods: Alt,     chars: "\x1bb"  }
  - { key: Right,   mods: Alt,     chars: "\x1bf"  }
  - { key: Left,    mods: Command, chars: "\x1bb"  }
  - { key: Right,   mods: Command, chars: "\x1bf"  }
