# Colors (Pencil Light)
 # primary:
   # background: '#ffffff'
   # foreground: '#424242'
 # normal:
   # black:   '#212121'
   # red:     '#c30771'
   # green:   '#10a778'
   # yellow:  '#a89c14'
   # blue:    '#008ec4'
   # magenta: '#523c79'
   # cyan:    '#20a5ba'
   # white:   '#e0e0e0'
 # bright:
   # black:   '#212121'
   # red:     '#fb007a'
   # green:   '#5fd7af'
   # yellow:  '#f3e430'
   # blue:    '#20bbfc'
   # magenta: '#6855de'
   # cyan:    '#4fb8cc'
   # white:   '#f1f1f1'
colors:
 primary:
   foreground: '#4a4b4e'
   background: '#eff0f2'
 # Normal colors
 normal:
   black: '#4a4b4e'
   red: '#a32a3a'
   green: '#206620'
   yellow: '#745300'
   blue: '#4b529a'
   magenta: '#8d377e'
   cyan: '#086784'
   white: '#e2e4e1'

 # Bright colors
 bright:
   black: '#686565'
   red: '#ae4e2a'
   green: '#1a7608'
   yellow: '#8d5b0a'
   blue: '#5c5bb2'
   magenta: '#8e47a8'
   cyan: '#106e8c'
   white: '#eff0f2'

font:
  normal:
    family: CodeNewRoman Nerd Font
    style: Book
  bold:
    family: CodeNewRoman Nerd Font
    style: Bold
  italic:
    family: CodeNewRoman Nerd Font
    style: Italic
  bold_italic:
    family: Source Code Pro
    style: Bold Italic
  size: 14.0
  offset:
    x: 1
    y: 2

window:
  padding:
    x: 10
    y: 2
  decorations: none

selection:
  save_to_clipboard: true

key_bindings:
  - { key: Left,    mods: Alt,     chars: "\x1bb"  }
  - { key: Right,   mods: Alt,     chars: "\x1bf"  }
  - { key: Left,    mods: Command, chars: "\x1bb"  }
  - { key: Right,   mods: Command, chars: "\x1bf"  }
