tap "1password/tap"
tap "superfly/tap"
brew "autoconf"
brew "automake"
brew "readline"
brew "awscli"
brew "icu4c@78"
brew "glib"
brew "cloc"
brew "cmake"
brew "libyaml"
brew "cocoapods"
brew "coreutils"
brew "fd"
brew "ffmpeg"
brew "fswatch"
brew "fzf"
brew "gh"
brew "harfbuzz"
brew "pango"
brew "ghostscript"
brew "git"
brew "git-standup"
brew "gnupg"
brew "libtool"
brew "graphviz"
brew "hivemind"
brew "htop"
brew "imagemagick"
brew "jpegoptim"
brew "jq"
brew "k6"
brew "kubernetes-cli"
brew "kops"
brew "kubectx"
brew "libaacs"
brew "libass"
brew "libxslt"
brew "lzip"
brew "mas"
brew "mise"
brew "mkcert"
brew "yt-dlp"
brew "mpv"
brew "mtr"
brew "neovim"
brew "node"
brew "nss"
brew "optipng"
brew "overmind"
brew "p7zip"
brew "pandoc"
brew "pgcli"
brew "pkgconf"
brew "protobuf"
brew "pyqt"
brew "python-yq"
brew "rcm"
brew "stern"
brew "subversion"
brew "svgo"
brew "telnet"
brew "the_silver_searcher"
brew "tree"
brew "tvnamer"
brew "unar"
brew "unixodbc"
brew "vim"
brew "watch"
brew "watchman"
brew "wget"
brew "wxwidgets"
brew "zsh"
brew "zsh-completions"
brew "superfly/tap/flyctl"
cask "1password"
cask "1password-cli"
cask "alfred"
cask "audacity"
cask "dash"
cask "discord"
cask "docker-desktop"
cask "expressvpn"
cask "firefox"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-source-code-pro"
cask "google-chrome"
cask "hook"
cask "iterm2@beta"
cask "mono-mdk"
cask "ngrok"
cask "obsidian"
cask "onyx"
cask "parsec"
cask "raycast"
cask "rectangle"
cask "safari-technology-preview"
cask "signal"
cask "slack"
cask "smcfancontrol"
cask "steam"
cask "swiftbar"
cask "tableplus"
cask "thunderbird"
cask "visual-studio-code"
cask "vlc"
cask "waterfox"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Adblock Plus", id: 1432731683
mas "Affinity Designer", id: 824171161
mas "Browser Ninja", id: 995838410
mas "Dark Noise", id: 1465439395
mas "Drafts", id: 1435957248
mas "Goodnotes", id: 1444383602
mas "JSON Peep", id: 1458969831
mas "Keynote", id: 409183694
mas "Monosnap", id: 540348655
mas "NextDNS", id: 1464122853
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PiPifier", id: 1160374471
mas "Reeder", id: 1529448980
mas "Slack", id: 803453959
mas "Tailscale", id: 1475387142
mas "Tot", id: 1491071483
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
vscode "1nvitr0.blocksort"
vscode "42crunch.vscode-openapi"
vscode "adamhartford.vscode-base64"
vscode "anthropic.claude-code"
vscode "bierner.color-info"
vscode "bierner.markdown-mermaid"
vscode "bradlc.vscode-tailwindcss"
vscode "damonsk.vscode-wardley-maps"
vscode "daverik.hextorgb"
vscode "dbaeumer.vscode-eslint"
vscode "denoland.vscode-deno"
vscode "eamodio.gitlens"
vscode "elmtooling.elm-ls-vscode"
vscode "esbenp.prettier-vscode"
vscode "fabiospampinato.vscode-diff"
vscode "gerane.theme-earthsong"
vscode "github.copilot-chat"
vscode "gurumukhi.selected-lines-count"
vscode "hbenl.vscode-test-explorer"
vscode "humao.rest-client"
vscode "jock.svg"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode.test-adapter-converter"
vscode "ms-vsliveshare.vsliveshare"
vscode "ms-vsliveshare.vsliveshare-pack"
vscode "prisma.prisma"
vscode "rangav.vscode-thunder-client"
vscode "redhat.vscode-yaml"
vscode "ronnidc.nunjucks"
vscode "shopify.ruby-lsp"
vscode "snyk-security.snyk-vulnerability-scanner"
vscode "stkb.rewrap"
vscode "stoplight.spectral"
vscode "takumii.markdowntable"
vscode "tamasfe.even-better-toml"
vscode "tyriar.lorem-ipsum"
vscode "vscodevim.vim"
vscode "vue.volar"
