tap "fewlines-education/tap"
tap "fewlinesco/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "k14s/tap"
tap "kdisneur/formulae"
tap "mongodb/brew"
tap "thoughtbot/formulae"
brew "autoconf"
brew "automake"
brew "openssl@1.1"
brew "readline"
brew "awscli"
brew "caddy"
brew "circleci"
brew "cloc"
brew "cmake"
brew "cocoapods"
brew "coreutils"
brew "dep"
brew "fd"
brew "libtool"
brew "ffmpeg"
brew "fswatch"
brew "fzf"
brew "ghostscript"
brew "git"
brew "git-standup"
brew "gnupg"
brew "graphviz"
brew "hivemind"
brew "htop"
brew "imagemagick"
brew "jpegoptim"
brew "jq"
brew "kubernetes-cli"
brew "kops"
brew "kubectx"
brew "libxslt"
brew "libyaml"
brew "lzip"
brew "mas"
brew "mkcert"
brew "mpv"
brew "mtr"
brew "neovim"
brew "nginx"
brew "nss"
brew "optipng"
brew "overmind"
brew "p7zip"
brew "pandoc"
brew "pgcli"
brew "postgresql"
brew "protobuf"
brew "pyqt"
brew "python-yq"
brew "rcm"
brew "stern"
brew "telnet"
brew "the_silver_searcher"
brew "tldr"
brew "tree"
brew "tvnamer"
brew "unixodbc"
brew "vim"
brew "watch"
brew "watchman"
brew "wget"
brew "wxmac"
brew "zsh"
brew "zsh-completions"
brew "fewlines-education/tap/sparta-cli"
brew "fewlinesco/tap/fwl_error"
brew "heroku/brew/heroku"
brew "k14s/tap/ytt"
brew "kdisneur/formulae/vimpack"
brew "mongodb/brew/mongodb-community"
cask "1password"
cask "alacritty"
cask "alfred"
cask "brave-browser"
cask "chromium"
cask "clickup"
cask "dash"
cask "discord"
cask "docker"
cask "encryptme"
cask "fantastical"
cask "firefox"
cask "firefox-developer-edition"
cask "font-codenewroman-nerd-font"
cask "font-fira-code"
cask "font-fira-mono"
cask "font-source-code-pro"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "kindle"
cask "mongodb-compass"
cask "mono-mdk"
cask "ngrok"
cask "obs"
cask "obsidian"
cask "omnifocus"
cask "onyx"
cask "parsec"
cask "pocket-casts"
cask "postman"
cask "rectangle"
cask "safari-technology-preview"
cask "setapp"
cask "shadow"
cask "signal"
cask "smcfancontrol"
cask "steam"
cask "visual-studio-code"
cask "vlc"
cask "yandex-cloud-cli"
mas "Affinity Designer", id: 824171161
mas "Drafts", id: 1435957248
mas "GarageBand", id: 682658836
mas "GoodNotes", id: 1444383602
mas "iMovie", id: 408981434
mas "JSONPeep", id: 1458969831
mas "Keynote", id: 409183694
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PiPifier", id: 1160374471
mas "Pocket", id: 568494494
mas "Reeder", id: 1529448980
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Tweetbot", id: 1384080005
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
